linter:
  rules:
    - always_declare_return_types
    - annotate_overrides
    - avoid_as
    - avoid_classes_with_only_static_members
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_return_types_on_setters
    - avoid_slow_async_io
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - control_flow_in_finally
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - iterable_contains_unrelated_type
    - library_names
    - library_prefixes
    - list_remove_unrelated_type
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - non_constant_identifier_names
    - constant_identifier_names
    - overridden_fields
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_contains
    - prefer_final_fields
    - prefer_final_locals
    - prefer_foreach
    - prefer_initializing_formals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_typing_uninitialized_variables
    - recursive_getters
    - slash_for_doc_comments
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - valid_regexps
    - avoid_returning_null_for_future
    - close_sinks
    - prefer_void_to_null
    - unnecessary_statements
    - avoid_returning_this
    - avoid_void_async
    - camel_case_extensions
    - cascade_invocations
    - only_throw_errors
    - one_member_abstracts
    - prefer_double_quotes
    - prefer_final_in_for_each
    - prefer_is_not_operator
    - prefer_inlined_adds
    - prefer_if_null_operators
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_spread_collections
    - sort_child_properties_last
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_parenthesis
    - unnecessary_string_interpolations
    - unnecessary_string_escapes
    - use_raw_strings
    - use_setters_to_change_properties
    - sort_pub_dependencies
    - use_string_buffers
    - use_to_and_as_if_applicable
    - void_checks
