name: app
description: A client for novels at Wuxiaworld.com
version: 3.0.0+19

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.15.9

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.3.4
  html: ^0.14.0
  path_provider: ^1.6.5
  share: ^0.6.3
  shared_preferences: ^0.5.6
  sqflite: ^1.2.0
  synchronized: ^2.2.0
  url_launcher: ^5.4.2
  flutter_hooks: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/novels.json
    - assets/images/1x1.png
  fonts:
    - family: Material Design Icons
      fonts:
        - asset: assets/fonts/material-design-icons.ttf
