name: app
description: A client for novels at Wuxiaworld.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.15.9

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.3.4
  html: ^0.14.0
  path_provider: ^0.4.0
  share: ^0.6.3
  shared_preferences: ^0.5.6
  sqflite: ^1.2.0
  synchronized: ^2.2.0
  url_launcher: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/novels.json
    - assets/images/1x1.png
  fonts:
    - family: Material Design Icons
      fonts:
        - asset: assets/fonts/material-design-icons.ttf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/open-sans-regular.ttf
        - asset: assets/fonts/open-sans-light.ttf
          weight: 300
        - asset: assets/fonts/open-sans-semi-bold.ttf
          weight: 600
        - asset: assets/fonts/open-sans-bold.ttf
          weight: 700
        - asset: assets/fonts/open-sans-extra-bold.ttf
          weight: 800
